name: Help_Maintenance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.4+4
  geolocator: ^10.1.0
  file_picker: ^4.0.0
  permission_handler: ^10.4.0
  url_launcher: ^6.0.13
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  dio: ^4.0.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/maintain_icon.png'
  adaptive_icon_background: 'assets/icons/maintain_icon.png'

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/login_eym_logo.png
    - assets/page-1/images/foundation-comments.png
    - assets/page-1/images/button-icon-button.png 
    - assets/page-1/images/ellipse-2.png
    - assets/page-1/images/ion-menu.png
    - assets/page-1/images/fluent-approvals-app-32-filled.png
    - assets/page-1/images/lucide-list.png
    - assets/page-1/images/icon-color.png
    - assets/page-1/images/button-icon-button-5tK.png
    - assets/page-1/images/akar-icons-arrow-back.png
    - assets/page-1/images/button-icon-button-gvT.png
    - assets/page-1/images/checkbox-icon.png
    - assets/page-1/images/union.png
    - assets/page-1/images/ellipse-2-kM5.png
    - assets/page-1/images/icon-color-uFD.png
    - assets/page-1/images/gridicons-user.png
    - assets/page-1/images/foundation-comments-tFZ.png
    - assets/page-1/images/union-5TD.png
    - assets/page-1/images/solar-chat-round-money-bold.png
    - assets/page-1/images/ellipse-2-dgK.png
    - assets/page-1/images/icon-color-pNs.png
    - assets/page-1/images/vector-1.png
    - assets/page-1/images/union-e1V.png
    - assets/page-1/images/ellipse-2-Gh5.png
    - assets/page-1/images/icon-color-7WX.png
    - assets/page-1/images/vector-1-BZq.png
    - assets/page-1/images/akar-icons-arrow-back-AAs.png
    - assets/page-1/images/lucide-list-ViF.png
    - assets/page-1/images/vector-1-LD5.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/shape.png
    - assets/page-1/images/union-1KD.png
    - assets/page-1/images/button-icon-button-nYf.png
    - assets/page-1/images/shape-Ujy.png
    - assets/page-1/images/ellipse-54.png
    - assets/page-1/images/leading-icon.png
    - assets/page-1/images/union-CcF.png
    - assets/page-1/images/shape-kZm.png
    - assets/page-1/images/checkbox-icon-qks.png
    - assets/page-1/images/vector-1-mtb.png
    - assets/page-1/images/ion-menu-rYX.png
    - assets/page-1/images/ellipse-2-6md.png
    - assets/page-1/images/vector-1-VDR.png
    - assets/page-1/images/jam-upload.png
    - assets/page-1/images/union-Jeb.png
    - assets/page-1/images/ellipse-2-e1d.png
    - assets/page-1/images/field.png
    - assets/page-1/images/union-BiF.png
    - assets/page-1/images/akar-icons-arrow-back-5Km.png
    - assets/page-1/images/akar-icons-arrow-back-Xkb.png
    - assets/page-1/images/leading-icon-vSB.png
    - assets/page-1/images/vector-1-ssD.png
    - assets/page-1/images/ellipse-2-uL3.png
    - assets/page-1/images/union-Wm5.png
    - assets/page-1/images/pdf-svgrepo-com-2.png
    - assets/page-1/images/timerfill0wght400grad0opsz24-1.png
    - assets/page-1/images/field-65d.png
    - assets/page-1/images/ion-menu-2mu.png
    - assets/page-1/images/group-35.png
    - assets/page-1/images/field-nSs.png
    - assets/page-1/images/field-4fH.png
    - assets/page-1/images/field-gEj.png
    - assets/page-1/images/ellipse-2-Ry1.png
    - assets/page-1/images/surface.png
    - assets/page-1/images/pdf-svgrepo-com-3.png
    - assets/page-1/images/field-9q1.png
    - assets/page-1/images/field-hbd.png
    - assets/page-1/images/icon-yp3.png
    - assets/page-1/images/auto-group-2xxr.png
    - assets/page-1/images/icon-color-ASb.png
    - assets/page-1/images/checkbox-icon-FGK.png
    - assets/page-1/images/ion-menu-kis.png
    - assets/page-1/images/shape-Emm.png
    - assets/page-1/images/ion-menu-Zp3.png
    - assets/page-1/images/surface-i3y.png
    - assets/page-1/images/leading-icon-QVd.png
    - assets/page-1/images/pdf-svgrepo-com-4.png
    - assets/page-1/images/icon-wM1.png
    - assets/page-1/images/vector-1-tsq.png
    - assets/page-1/images/shape-PNf.png
    - assets/page-1/images/vector-1-STy.png
    - assets/page-1/images/icon-color-4Vu.png
    - assets/page-1/images/jam-upload-raB.png
    - assets/page-1/images/gridicons-user-Ujy.png
    - assets/page-1/images/vector-1-2sH.png
    - assets/page-1/images/surface-S39.png
    - assets/page-1/images/union-Gnb.png
    - assets/page-1/images/union-Dr7.png
    - assets/page-1/images/pdf-svgrepo-com-5.png
    - assets/page-1/images/field-gmd.png
    - assets/page-1/images/icon-RZR.png
    - assets/page-1/images/vector-1-DJo.png
    - assets/page-1/images/auto-group-p3vf.png
    - assets/page-1/images/ellipse-2-QaK.png
    - assets/page-1/images/field-sHR.png
    - assets/page-1/images/solar-chat-round-money-bold-R43.png
    - assets/page-1/images/checkbox-icon-QDd.png
    - assets/page-1/images/vector-1-VT5.png
    - assets/page-1/images/ellipse-54-bg.png
    - assets/page-1/images/icon-color-UHV.png
    - assets/page-1/images/checkbox-icon-1tK.png
    - assets/page-1/images/icon-color-xiB.png
    - assets/page-1/images/group-35-aoH.png
    - assets/page-1/images/union-zJb.png
    - assets/page-1/images/ellipse-54-bg-DzX.png
    - assets/page-1/images/field-15Z.png
    - assets/page-1/images/ellipse-54-bg-E3y.png
    - assets/page-1/images/ellipse-2-xWb.png
    - assets/page-1/images/shape-Kfu.png
    - assets/page-1/images/rectangle-29-bg.png
    - assets/page-1/images/ellipse-2-SnK.png
    - assets/page-1/images/rectangle-29-bg-Aa3.png
    - assets/page-1/images/field-ewZ.png
    - assets/page-1/images/ellipse-54-bg-xJb.png
    - assets/page-1/images/rectangle-29-bg-d99.png
    - assets/page-1/images/rectangle-29-bg-fK5.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
